"""Phase 5C: concise PDF and Word exports for one view or an entire investigation.

The PDF exporter intentionally uses Matplotlib, which VizCreate already requires for
chart rendering. This avoids adding ReportLab as a second PDF dependency.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from io import BytesIO
from textwrap import wrap
from typing import Iterable, Optional, Sequence

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


@dataclass
class ReportModel:
    """A minimal, presentation-ready representation of one current analysis."""

    question: str
    chart_png: bytes
    analyst_summary: str
    key_findings: list[str] = field(default_factory=list)
    supporting_evidence: list[str] = field(default_factory=list)
    communication_preview: str = ""
    generated_at: datetime = field(default_factory=datetime.now)
    title: str = "VizCreate Analysis Report"


def _clean_items(items: Optional[Iterable[str]]) -> list[str]:
    cleaned: list[str] = []
    for item in items or []:
        text = " ".join(str(item or "").split())
        if text and text not in cleaned:
            cleaned.append(text)
    return cleaned


def build_analyst_summary(
    *,
    question: str,
    chart_description: str,
    evidence_overview: str,
    evidence_findings: Optional[Iterable[str]] = None,
    max_sentences: int = 4,
) -> str:
    """Create a restrained summary from outputs already shown in the viewer."""

    candidates = _clean_items(
        [chart_description, evidence_overview, *list(evidence_findings or [])]
    )
    if not candidates:
        return (
            "This report summarizes the current VizCreate analysis. "
            "Review the visualization and supporting evidence before drawing conclusions."
        )

    selected: list[str] = []
    for text in candidates:
        if len(selected) >= max_sentences:
            break
        if text[-1:] not in ".!?":
            text += "."
        selected.append(text)

    closing = (
        "These results describe the current filtered data and should be interpreted "
        "as evidence for further investigation rather than as a causal conclusion."
    )
    if len(selected) < max_sentences and not any("causal" in s.lower() for s in selected):
        selected.append(closing)
    return " ".join(selected[:max_sentences])


def _display_date(value: datetime) -> str:
    """Return a Windows-safe month-day-year string without a leading-zero day."""
    return f"{value.strftime('%B')} {value.day}, {value.year}"


def _pdf_footer(fig, generated_at: datetime) -> None:
    fig.lines.append(
        plt.Line2D([0.10, 0.90], [0.080, 0.080], transform=fig.transFigure,
                   linewidth=0.6, color="#B8B8B8")
    )
    fig.text(0.5, 0.060, "Generated by VizCreate", ha="center", fontsize=8.5,
             fontweight="bold", color="#444444")
    fig.text(0.5, 0.046, "Educational Data Analysis Assistant", ha="center",
             fontsize=8, fontstyle="italic", color="#444444")
    fig.text(0.5, 0.032, "University of Wyoming College of Education", ha="center",
             fontsize=8, color="#444444")
    fig.text(0.5, 0.018, f"Report generated: {_display_date(generated_at)}", ha="center",
             fontsize=7.5, fontstyle="italic", color="#555555")


def _wrapped_lines(text: str, width: int = 95) -> list[str]:
    paragraphs = str(text or "").splitlines() or [""]
    lines: list[str] = []
    for paragraph in paragraphs:
        paragraph = " ".join(paragraph.split())
        lines.extend(wrap(paragraph, width=width) if paragraph else [""])
    return lines


def _draw_text_section(fig, y: float, heading: str, text: str, *, width: int = 95) -> float:
    fig.text(0.10, y, heading, fontsize=12, fontweight="bold", color="#2E2118", va="top")
    y -= 0.026
    for line in _wrapped_lines(text, width=width):
        fig.text(0.10, y, line, fontsize=9.4, color="#222222", va="top")
        y -= 0.018
    return y - 0.012


def _draw_bullet_section(fig, y: float, heading: str, items: Iterable[str]) -> float:
    cleaned = _clean_items(items)
    if not cleaned:
        return y
    fig.text(0.10, y, heading, fontsize=12, fontweight="bold", color="#2E2118", va="top")
    y -= 0.027
    for item in cleaned:
        lines = _wrapped_lines(item, width=88)
        for index, line in enumerate(lines):
            prefix = "• " if index == 0 else "  "
            fig.text(0.115, y, prefix + line, fontsize=9.3, color="#222222", va="top")
            y -= 0.018
        y -= 0.004
    return y - 0.010


def build_pdf_report(model: ReportModel) -> bytes:
    """Return a concise, shareable PDF report using existing Matplotlib support."""

    output = BytesIO()
    with PdfPages(output) as pdf:
        # Page 1 mirrors the main viewer: title, question, chart, analyst summary.
        fig = plt.figure(figsize=(8.5, 11))
        fig.patch.set_facecolor("white")
        fig.text(0.5, 0.955, model.title, ha="center", va="top", fontsize=19,
                 fontweight="bold", color="#2E2118")
        fig.text(0.10, 0.910, "Question", fontsize=12, fontweight="bold",
                 color="#2E2118", va="top")
        question_lines = _wrapped_lines(model.question or "Question not recorded.", width=92)
        question_text = "\n".join(question_lines)
        fig.text(0.11, 0.882, question_text, fontsize=9.7, color="#222222", va="top",
                 bbox=dict(boxstyle="round,pad=0.55", facecolor="#F7F7F7",
                           edgecolor="#D7D7D7", linewidth=0.7))

        fig.text(0.10, 0.820, "Visualization", fontsize=12, fontweight="bold",
                 color="#2E2118", va="top")
        if model.chart_png:
            try:
                image = mpimg.imread(BytesIO(model.chart_png), format="png")
                ax = fig.add_axes([0.10, 0.385, 0.80, 0.405])
                ax.imshow(image)
                ax.axis("off")
            except Exception:
                fig.text(0.10, 0.765, "The chart image could not be embedded.", fontsize=9.5)

        y = 0.350
        y = _draw_text_section(fig, y, "Analyst Summary", model.analyst_summary, width=96)
        _pdf_footer(fig, model.generated_at)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        # Page 2 contains only viewer sections that have content.
        if model.key_findings or model.supporting_evidence or model.communication_preview:
            fig = plt.figure(figsize=(8.5, 11))
            fig.patch.set_facecolor("white")
            fig.text(0.5, 0.955, model.title, ha="center", va="top", fontsize=17,
                     fontweight="bold", color="#2E2118")
            y = 0.905
            y = _draw_bullet_section(fig, y, "Key Findings", model.key_findings)
            y = _draw_bullet_section(fig, y, "Supporting Evidence", model.supporting_evidence)
            if model.communication_preview:
                if y < 0.22:
                    _pdf_footer(fig, model.generated_at)
                    pdf.savefig(fig, bbox_inches="tight")
                    plt.close(fig)
                    fig = plt.figure(figsize=(8.5, 11))
                    fig.patch.set_facecolor("white")
                    y = 0.925
                _draw_text_section(fig, y, "Communication Preview", model.communication_preview, width=96)
            _pdf_footer(fig, model.generated_at)
            pdf.savefig(fig, bbox_inches="tight")
            plt.close(fig)

    return output.getvalue()


def _set_cell_border(paragraph) -> None:
    p = paragraph._p
    p_pr = p.get_or_add_pPr()
    borders = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "4")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "B8B8B8")
    borders.append(bottom)
    p_pr.append(borders)


def build_word_report(model: ReportModel) -> bytes:
    """Return a concise, editable DOCX report as bytes."""

    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.55)
    section.bottom_margin = Inches(0.72)
    section.left_margin = Inches(0.72)
    section.right_margin = Inches(0.72)

    normal = document.styles["Normal"]
    normal.font.name = "Aptos"
    normal.font.size = Pt(10)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(model.title)
    run.bold = True
    run.font.size = Pt(19)
    run.font.color.rgb = RGBColor(46, 33, 24)

    def add_heading(text: str) -> None:
        paragraph = document.add_paragraph()
        paragraph.paragraph_format.space_before = Pt(8)
        paragraph.paragraph_format.space_after = Pt(3)
        run = paragraph.add_run(text)
        run.bold = True
        run.font.size = Pt(12.5)
        run.font.color.rgb = RGBColor(46, 33, 24)

    add_heading("Question")
    question = document.add_paragraph(model.question or "Question not recorded.")
    question.paragraph_format.left_indent = Inches(0.12)
    question.paragraph_format.right_indent = Inches(0.12)

    add_heading("Visualization")
    if model.chart_png:
        picture_p = document.add_paragraph()
        picture_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        picture_p.add_run().add_picture(BytesIO(model.chart_png), width=Inches(6.65))

    add_heading("Analyst Summary")
    document.add_paragraph(model.analyst_summary)

    if model.key_findings:
        add_heading("Key Findings")
        for item in model.key_findings:
            document.add_paragraph(item, style="List Bullet")

    if model.supporting_evidence:
        add_heading("Supporting Evidence")
        for item in model.supporting_evidence:
            document.add_paragraph(item, style="List Bullet")

    if model.communication_preview:
        add_heading("Communication Preview")
        document.add_paragraph(model.communication_preview)

    footer = section.footer
    footer_p = footer.paragraphs[0]
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_cell_border(footer_p)
    r1 = footer_p.add_run("Generated by VizCreate\n")
    r1.bold = True
    r1.font.size = Pt(8.5)
    r2 = footer_p.add_run("Educational Data Analysis Assistant\n")
    r2.italic = True
    r2.font.size = Pt(8)
    r3 = footer_p.add_run("University of Wyoming College of Education\n")
    r3.font.size = Pt(8)
    r4 = footer_p.add_run(f"Report generated: {_display_date(model.generated_at)}")
    r4.italic = True
    r4.font.size = Pt(7.5)

    output = BytesIO()
    document.save(output)
    return output.getvalue()



def _investigation_title(models: Sequence[ReportModel]) -> str:
    return "VizCreate Investigation Report" if len(models) > 1 else (models[0].title if models else "VizCreate Analysis Report")


def build_pdf_investigation(models: Sequence[ReportModel]) -> bytes:
    """Return a multi-analysis PDF in chronological investigation order.

    Each stored analysis keeps the same concise viewer-based layout used by the
    current-view report. This intentionally avoids a separate, more complicated
    investigation-report design.
    """
    clean_models = [model for model in models if model is not None]
    if not clean_models:
        raise ValueError("At least one report model is required.")
    if len(clean_models) == 1:
        return build_pdf_report(clean_models[0])

    output = BytesIO()
    report_title = _investigation_title(clean_models)
    with PdfPages(output) as pdf:
        for index, model in enumerate(clean_models, start=1):
            fig = plt.figure(figsize=(8.5, 11))
            fig.patch.set_facecolor("white")
            fig.text(0.5, 0.962, report_title, ha="center", va="top", fontsize=18,
                     fontweight="bold", color="#2E2118")
            fig.text(0.5, 0.932, f"Analysis {index} of {len(clean_models)}", ha="center",
                     va="top", fontsize=9, color="#666666")
            fig.text(0.10, 0.895, "Question", fontsize=12, fontweight="bold",
                     color="#2E2118", va="top")
            question_text = "\n".join(_wrapped_lines(model.question or "Question not recorded.", width=92))
            fig.text(0.11, 0.868, question_text, fontsize=9.7, color="#222222", va="top",
                     bbox=dict(boxstyle="round,pad=0.55", facecolor="#F7F7F7",
                               edgecolor="#D7D7D7", linewidth=0.7))
            fig.text(0.10, 0.807, "Visualization", fontsize=12, fontweight="bold",
                     color="#2E2118", va="top")
            if model.chart_png:
                try:
                    image = mpimg.imread(BytesIO(model.chart_png), format="png")
                    ax = fig.add_axes([0.10, 0.380, 0.80, 0.395])
                    ax.imshow(image)
                    ax.axis("off")
                except Exception:
                    fig.text(0.10, 0.750, "The chart image could not be embedded.", fontsize=9.5)
            y = 0.345
            _draw_text_section(fig, y, "Analyst Summary", model.analyst_summary, width=96)
            _pdf_footer(fig, model.generated_at)
            pdf.savefig(fig, bbox_inches="tight")
            plt.close(fig)

            if model.key_findings or model.supporting_evidence or model.communication_preview:
                fig = plt.figure(figsize=(8.5, 11))
                fig.patch.set_facecolor("white")
                fig.text(0.5, 0.962, report_title, ha="center", va="top", fontsize=16,
                         fontweight="bold", color="#2E2118")
                fig.text(0.5, 0.934, f"Analysis {index}: Supporting Detail", ha="center",
                         va="top", fontsize=9, color="#666666")
                y = 0.895
                y = _draw_bullet_section(fig, y, "Key Findings", model.key_findings)
                y = _draw_bullet_section(fig, y, "Supporting Evidence", model.supporting_evidence)
                if model.communication_preview:
                    if y < 0.22:
                        _pdf_footer(fig, model.generated_at)
                        pdf.savefig(fig, bbox_inches="tight")
                        plt.close(fig)
                        fig = plt.figure(figsize=(8.5, 11))
                        fig.patch.set_facecolor("white")
                        fig.text(0.5, 0.962, report_title, ha="center", va="top", fontsize=16,
                                 fontweight="bold", color="#2E2118")
                        fig.text(0.5, 0.934, f"Analysis {index}: Communication Preview", ha="center",
                                 va="top", fontsize=9, color="#666666")
                        y = 0.895
                    _draw_text_section(fig, y, "Communication Preview", model.communication_preview, width=96)
                _pdf_footer(fig, model.generated_at)
                pdf.savefig(fig, bbox_inches="tight")
                plt.close(fig)
    return output.getvalue()


def _configure_word_document(document: Document) -> None:
    section = document.sections[0]
    section.top_margin = Inches(0.55)
    section.bottom_margin = Inches(0.72)
    section.left_margin = Inches(0.72)
    section.right_margin = Inches(0.72)
    normal = document.styles["Normal"]
    normal.font.name = "Aptos"
    normal.font.size = Pt(10)


def _add_word_footer(section, generated_at: datetime) -> None:
    footer = section.footer
    footer_p = footer.paragraphs[0]
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_cell_border(footer_p)
    r1 = footer_p.add_run("Generated by VizCreate\n")
    r1.bold = True
    r1.font.size = Pt(8.5)
    r2 = footer_p.add_run("Educational Data Analysis Assistant\n")
    r2.italic = True
    r2.font.size = Pt(8)
    r3 = footer_p.add_run("University of Wyoming College of Education\n")
    r3.font.size = Pt(8)
    r4 = footer_p.add_run(f"Report generated: {_display_date(generated_at)}")
    r4.italic = True
    r4.font.size = Pt(7.5)


def build_word_investigation(models: Sequence[ReportModel]) -> bytes:
    """Return an editable Word report containing every completed analysis."""
    clean_models = [model for model in models if model is not None]
    if not clean_models:
        raise ValueError("At least one report model is required.")
    if len(clean_models) == 1:
        return build_word_report(clean_models[0])

    document = Document()
    _configure_word_document(document)
    report_title = _investigation_title(clean_models)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(report_title)
    run.bold = True
    run.font.size = Pt(19)
    run.font.color.rgb = RGBColor(46, 33, 24)

    def add_heading(text: str) -> None:
        paragraph = document.add_paragraph()
        paragraph.paragraph_format.space_before = Pt(8)
        paragraph.paragraph_format.space_after = Pt(3)
        run = paragraph.add_run(text)
        run.bold = True
        run.font.size = Pt(12.5)
        run.font.color.rgb = RGBColor(46, 33, 24)

    for index, model in enumerate(clean_models, start=1):
        if index > 1:
            document.add_page_break()
        marker = document.add_paragraph()
        marker.alignment = WD_ALIGN_PARAGRAPH.CENTER
        marker_run = marker.add_run(f"Analysis {index} of {len(clean_models)}")
        marker_run.italic = True
        marker_run.font.size = Pt(9)
        marker_run.font.color.rgb = RGBColor(100, 100, 100)

        add_heading("Question")
        question = document.add_paragraph(model.question or "Question not recorded.")
        question.paragraph_format.left_indent = Inches(0.12)
        question.paragraph_format.right_indent = Inches(0.12)

        add_heading("Visualization")
        if model.chart_png:
            picture_p = document.add_paragraph()
            picture_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            picture_p.add_run().add_picture(BytesIO(model.chart_png), width=Inches(6.65))

        add_heading("Analyst Summary")
        document.add_paragraph(model.analyst_summary)

        if model.key_findings:
            add_heading("Key Findings")
            for item in model.key_findings:
                document.add_paragraph(item, style="List Bullet")
        if model.supporting_evidence:
            add_heading("Supporting Evidence")
            for item in model.supporting_evidence:
                document.add_paragraph(item, style="List Bullet")
        if model.communication_preview:
            add_heading("Communication Preview")
            document.add_paragraph(model.communication_preview)

    _add_word_footer(document.sections[0], clean_models[-1].generated_at)
    output = BytesIO()
    document.save(output)
    return output.getvalue()
